name: Build gripss Docker image

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: "Docker image tag, If omitted will use github short sha"
        required: false
        type: string

permissions:
  id-token: write # Required for assuming an AWS role
  contents: read # Required for actions/checkout

env:
#  AWS_REGION: us-east-1
#  AWS_ROLE_NAME: github-actions-ecr
#  AWS_ACCOUNT: 337532070941
#
#  GCP_WORKLOAD_IDENTITY_PROVIDER: projects/55428976747/locations/global/workloadIdentityPools/devops-pool/providers/devops-pool-provider
#  GCP_SERVICE_ACCOUNT: gcr-push-sa@ultima-data-307918.iam.gserviceaccount.com

  IMAGE: gripss

jobs:

  build:
    uses: Ultimagen/ugbio-utils/.github/workflows/docker-build-push.yml@DATA-8557-use-common-build-docker-action
    secrets: inherit
    with:
      git-repo: ${{ github.repository }}
      git-ref: ${{ github.ref_name }}
      docker-image: ${{  env.IMAGE }}
      docker-file: gripss/Dockerfile
      docker-tag: ${{ inputs.image-tag }}
      base-branch: master
